name: ecomerceapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1+8
  google_sign_in: ^4.0.4
  generic_bloc_provider: ^1.0.8
  cloud_firestore: ^0.13.0+1
  firebase_storage:
  carousel_slider: ^1.3.0
  image_picker: ^0.5.4+3
  cached_network_image: ^2.0.0
  flutter_slidable: ^0.5.3
  local_auth: ^0.5.2+3
  get_it: ^1.0.3+2
  badges: ^0.0.6
  stripe_payment: ^1.0.6
  dio: ^3.0.8
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/images/
    - images/chewy/
    - images/products/
    - images/products/1.jpg
    - images/products/2.jpg
    - images/products/3.jpg
    - images/products/4.jpg
    - images/products/5.jpg
    - images/products/6.jpg
    - images/images/products_LA/1.jpeg
    - images/images/products_LA/2.jpg
    - images/images/products_LA/3.jpg
    - images/images/products_LA/4.jpg
    - images/images/products_LA/5.jpg
    - images/images/products_LA/6.jpg
    - images/images/products_LA/7.jpg
    - images/images/products_LA/8.jpg
    - images/images/products_LA/9.jpg
    - images/images/products_LA/16.jpg
    - images/images/products_LA/17.jpg
    - images/images/products_LA/15.jpg
    - images/images/icon/perros.png
    - images/images/icon/gatos.jpg
    # aqui va la mochila
    - images/products/cat_backpack/1.jpg
    - images/products/cat_backpack/2.jpg
    - images/products/cat_backpack/3.jpg
    - images/products/cat_backpack/4.jpg
    - images/products/cat_backpack/5.jpg
    - images/products/cat_backpack/6.jpeg
    # aqui va el paw print pad
    - images/products/paw_print_pad/1.jpg
    - images/products/paw_print_pad/2.jpg
    - images/products/paw_print_pad/3.jpg
    - images/products/paw_print_pad/4.jpg
    - images/products/paw_print_pad/5.jpg
    - images/products/paw_print_pad/6.jpg

    # aqui va el dog paw clena
    - images/products/dog_paw_clean/1.jpg
    - images/products/dog_paw_clean/2.jpg
    - images/products/dog_paw_clean/3.jpg
    - images/products/dog_paw_clean/4.jpg
    - images/products/dog_paw_clean/5.jpg
    - images/products/dog_paw_clean/6.jpg
    - images/products/dog_paw_clean/7.jpg
    - images/products/dog_paw_clean/8.jpg
    - images/products/dog_paw_clean/9.jpg
    - images/products/dog_paw_clean/10.jpg
    - images/products/dog_paw_clean/11.jpg

    # aqui va el beds for pets
    - images/products/beds_for_pets/1.jpg
    - images/products/beds_for_pets/2.jpg
    - images/products/beds_for_pets/3.jpg
    - images/products/beds_for_pets/4.jpg
    - images/products/beds_for_pets/5.jpg
    - images/products/beds_for_pets/6.jpg
    - images/products/beds_for_pets/7.jpg

    # aqui va el hair remover
    - images/products/hair_remover/1.jpg
    - images/products/hair_remover/2.jpg
    - images/products/hair_remover/3.jpg
    - images/products/hair_remover/4.jpg
    - images/products/hair_remover/5.jpg
    - images/products/hair_remover/6.jpg
    - images/products/hair_remover/7.jpg
    - images/products/hair_remover/8.jpg


    # aqui va el portable water bottle
    - images/products/portable_water_bottle/1.jpg
    - images/products/portable_water_bottle/2.jpg
    - images/products/portable_water_bottle/3.jpg
    - images/products/portable_water_bottle/4.jpg
    - images/products/portable_water_bottle/5.jpg
    - images/products/portable_water_bottle/6.jpg
    - images/products/portable_water_bottle/7.jpg

    # aqui va elbags dispenser
    - images/products/bags_dispenser/1.jpg
    - images/products/bags_dispenser/2.jpg
    - images/products/bags_dispenser/3.jpg
    - images/products/bags_dispenser/4.jpg
    - images/products/bags_dispenser/5.jpg
    - images/products/bags_dispenser/6.jpg
    - images/products/bags_dispenser/7.jpg
    - images/products/bags_dispenser/8.jpg

    # aqui va el food treat ball
    - images/products/food_treat_ball/1.jpg
    - images/products/food_treat_ball/2.jpg
    - images/products/food_treat_ball/3.jpg
    - images/products/food_treat_ball/4.jpg
    - images/products/food_treat_ball/5.jpg
    - images/products/food_treat_ball/6.jpg
    - images/products/food_treat_ball/7.jpg

    # aqui va el dog carrier backpack
    - images/products/dog_carrier_backpack/1.jpg

    # aqui va el dog cpoop rolls
    - images/products/poop_rolls/1.jpg

    # aqui va el waterproof cat backpack
    - images/products/waterproof_cat_backpack/1.jpg
    - images/products/waterproof_cat_backpack/2.jpg
    - images/products/waterproof_cat_backpack/3.jpg
    - images/products/waterproof_cat_backpack/4.jpg
    - images/products/waterproof_cat_backpack/5.jpg
    - images/products/waterproof_cat_backpack/6.jpg
    - images/products/waterproof_cat_backpack/7.jpg
    - images/products/waterproof_cat_backpack/8.jpg

    # aqui va el finger t
    - images/products/finger_t/1.jpg
    - images/products/finger_t/2.jpg
    - images/products/finger_t/3.jpg

    #iconos
    - images/iconos/google.jpg

    - images/assets/

    - assets/img/people.jpg
    - assets/img/ann.jpg
    - assets/img/girl.jpg
    - assets/img/mountain.jpeg
    - assets/img/beach.jpeg
    - assets/img/beach_palm.jpeg
    - assets/img/mountain_stars.jpeg
    - assets/img/sunset.jpeg
    - assets/img/river.jpeg

    #banner
    - images/images/banner/perrobanner1.png
    - images/images/banner/banner2.jpg
    - images/images/banner/banner3.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
